#!/usr/bin/env python3
"""Subprocess E2E tests for the registry validator and index generator."""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]


def _write_yaml(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")


class RegistryE2ETests(unittest.TestCase):
    def _make_workspace(self) -> tuple[Path, Path, Path, Path]:
        temp_dir = Path(tempfile.mkdtemp(prefix="omega-registry-e2e-"))
        scripts_dir = temp_dir / "scripts"
        registry_dir = temp_dir / "registry"
        domains_dir = registry_dir / "domains"
        collections_dir = registry_dir / "collections"
        scripts_dir.mkdir(parents=True)
        domains_dir.mkdir(parents=True)
        collections_dir.mkdir(parents=True)

        for script_name in ("generate_index.py", "validate_registry.py"):
            source = REPO_ROOT / "scripts" / script_name
            target = scripts_dir / script_name
            target.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")

        return temp_dir, scripts_dir, domains_dir, collections_dir

    def test_generate_index_script_writes_current_triage_counts(self) -> None:
        workspace, scripts_dir, domains_dir, _ = self._make_workspace()
        try:
            _write_yaml(
                domains_dir / "number-theory.yaml",
                {
                    "problems": [
                        {
                            "id": "erdos-straus",
                            "name": "Erdos-Straus",
                            "status": "open",
                            "statement": "4/n = 1/x + 1/y + 1/z",
                            "tags": ["egyptian-fractions"],
                            "ai_triage": {"tier": "T1-computational", "amenability_score": 8},
                        },
                        {
                            "id": "goldbach-conjecture",
                            "name": "Goldbach",
                            "status": "open",
                            "statement": "Every even number > 2 is the sum of two primes",
                            "tags": ["primes"],
                            "ai_triage": {"tier": "T3-pattern", "amenability_score": 4},
                        },
                    ]
                },
            )
            _write_yaml(
                workspace / "registry" / "triage-matrix.yaml",
                {
                    "tier_1_computational": [{"id": "erdos-straus", "score": 8}],
                    "tier_2_experimental": [],
                    "tier_3_pattern": [{"id": "goldbach-conjecture", "score": 4}],
                    "tier_4_structural": [],
                    "tier_5_foundational": [],
                },
            )

            result = subprocess.run(
                [sys.executable, str(scripts_dir / "generate_index.py")],
                cwd=workspace,
                capture_output=True,
                text=True,
                check=True,
            )

            index_path = workspace / "registry" / "index.yaml"
            self.assertIn("Updated", result.stdout)
            self.assertTrue(index_path.exists())
            index_text = index_path.read_text(encoding="utf-8")
            self.assertIn("# Generated by: scripts/generate_index.py", index_text)
            self.assertIn("triage_matrix_entries: 2", index_text)
        finally:
            shutil.rmtree(workspace)

    def test_validate_registry_script_passes_for_consistent_workspace(self) -> None:
        workspace, scripts_dir, domains_dir, _ = self._make_workspace()
        try:
            _write_yaml(
                domains_dir / "geometry.yaml",
                {
                    "problems": [
                        {
                            "id": "kobon-triangles",
                            "name": "Kobon triangles",
                            "status": "open",
                            "statement": "maximize triangles",
                            "tags": ["geometry"],
                            "ai_triage": {"tier": "T1-computational", "amenability_score": 8},
                        }
                    ]
                },
            )
            _write_yaml(
                workspace / "registry" / "triage-matrix.yaml",
                {
                    "tier_1_computational": [{"id": "kobon-triangles", "score": 8}],
                    "tier_2_experimental": [],
                    "tier_3_pattern": [],
                    "tier_4_structural": [],
                    "tier_5_foundational": [],
                },
            )

            result = subprocess.run(
                [sys.executable, str(scripts_dir / "validate_registry.py")],
                cwd=workspace,
                capture_output=True,
                text=True,
                check=False,
            )

            self.assertEqual(result.returncode, 0)
            self.assertIn("Registry validation passed (0 errors)", result.stdout)
        finally:
            shutil.rmtree(workspace)

    def test_validate_registry_script_fails_for_tier_drift(self) -> None:
        workspace, scripts_dir, domains_dir, _ = self._make_workspace()
        try:
            _write_yaml(
                domains_dir / "game-theory.yaml",
                {
                    "problems": [
                        {
                            "id": "chess-first-move",
                            "name": "Solving chess",
                            "status": "open",
                            "statement": "perfect play outcome",
                            "tags": ["chess"],
                            "ai_triage": {"tier": "T1-computational", "amenability_score": 3},
                        }
                    ]
                },
            )
            _write_yaml(
                workspace / "registry" / "triage-matrix.yaml",
                {
                    "tier_1_computational": [],
                    "tier_2_experimental": [],
                    "tier_3_pattern": [],
                    "tier_4_structural": [],
                    "tier_5_foundational": [],
                },
            )

            result = subprocess.run(
                [sys.executable, str(scripts_dir / "validate_registry.py")],
                cwd=workspace,
                capture_output=True,
                text=True,
                check=False,
            )

            self.assertEqual(result.returncode, 1)
            self.assertIn("requires tier 'T3-pattern'", result.stdout)
            self.assertIn("Missing triaged domain ID 'chess-first-move'", result.stdout)
        finally:
            shutil.rmtree(workspace)


if __name__ == "__main__":
    unittest.main()